oc_platform_homepage:
    path:     /hello
    defaults: { _controller: OCPlatformBundle:Advert:index }

oc_platform_hello_name:
    path:    /hello/{nom}
    defaults:  { _controller:  OCPlatformBundle:Advert:hello }

oc_platform_home:
    path:  /{page}
    defaults:
      _controller:  OCPlatformBundle:Advert:index
      page:  1
    requirements:
       page:  \d*

oc_platform_view:
    path:     /advert/{id}
    defaults:
      _controller: OCPlatformBundle:Advert:view
    requirements:
       id: \d+

oc_platform_view_application:
    path:     /advert/{id}/application
    defaults:
      _controller: OCPlatformBundle:Advert:viewApplication
    requirements:
       id: \d+

oc_platform_add:
    path:    /add
    defaults:
      _controller:  OCPlatformBundle:Advert:add

oc_platform_add_form:
    path:    /form
    defaults:
      _controller:    OCPlatformBundle:Advert:addForm

oc_platform_add_form_nodate:
    path:    /form/date
    defaults:
      _controller:    OCPlatformBundle:Advert:formNodate

oc_platform_edit:
    path:    /edit/{id}
    defaults:
       _controller: OCPlatformBundle:Advert:edit
    requirements:
       id:  \d+

oc_platform_edit_Image:
    path:    /edit/image/{advertId}
    defaults:
        _controller:  OCPlatformBundle:Advert:editImage
    requirements:
        advertId:  \d+

oc_platform_delete:
    path:    /delete/{id}
    defaults:
       _controller:  OCPlatformBundle:Advert:delete
    requirements:
       id:  \d+

oc_platform_add_to_category:
    path:    /add/advert/{id}/category
    defaults:
        _controller:  OCPlatformBundle:Advert:addToCategory
    requirements:
        id:    \d+

oc_platform_update_advert:
    path:  /update/{id}/{titre}/{content}
    defaults:
        _controller:  OCPlatformBundle:Advert:updateAdvert
    requirements:
        id:    \d+